Change text from 'ignoring' to 'skipping'.

diff --git a/parse_ini b/parse_ini
--- a/parse_ini
+++ b/parse_ini
@@ -350,15 +350,15 @@ parse_ini() {
     if [[ "${LINE:0:1}" == "[" ]]; then		# Found the beginning of a section definition.
       # Check the format of the section definition.
       if [[ "${LINE: -1:1}" != "]" ]]; then
-        echo "${0##*/}: line $LINENUMBER: unmatched [ in section definition - ignoring section" >&2
+        echo "${0##*/}: line $LINENUMBER: unmatched [ in section definition - skipping section" >&2
         IGNORE_SECTION=1
         continue
       elif [[ "${LINE:1:-1}" =~ [^$ACCEPTABLE_CHARS\[\]]* ]]; then
-        echo "${0##*/}: line $LINENUMBER: invalid characters in section definition - ignoring section" >&2
+        echo "${0##*/}: line $LINENUMBER: invalid characters in section definition - skipping section" >&2
         IGNORE_SECTION=1
         continue
       elif [[ -z "${LINE:1:-1}" ]] || [[ "${LINE:1:-1}" =~ ^[[:blank:]]+$ ]]; then
-        echo "${0##*/}: line $LINENUMBER: empty section definition - ignoring section" >&2
+        echo "${0##*/}: line $LINENUMBER: empty section definition - skipping section" >&2
         IGNORE_SECTION=1
         continue
       else
@@ -393,7 +393,7 @@ parse_ini() {
           for SECTION in "${SEEN_SECTIONS[@]}"; do
             if [[ "$CURRENT_SECTION" == "$SECTION" ]]; then
               # It's a section we've seen before - don't process it.
-              echo "${0##*/}: line $LINENUMBER: repeated section name - ignoring section" >&2
+              echo "${0##*/}: line $LINENUMBER: repeated section name - skipping section" >&2
               IGNORE_SECTION=1
               continue 2
             fi
@@ -415,7 +415,7 @@ parse_ini() {
           # Strip the quotes as they're not needed.
           LINE="${LINE:1:-1}"
         else
-          echo "${0##*/}: line $LINENUMBER: unmatched quotes - ignoring property" >&2
+          echo "${0##*/}: line $LINENUMBER: unmatched quotes - skipping property" >&2
           continue
         fi
       fi
@@ -440,7 +440,7 @@ parse_ini() {
       if ((USE_BOOLEANS == 1)); then
         printf "%s%s%s[\"%s\"]=\"%s\"\\n" "$PREFIX" "${PREFIX:+$DELIM}" "$CURRENT_SECTION" "$LINE" "$BOOL_VALUE"
       else
-        echo "${0##*/}: line $LINENUMBER: key without a value - ignoring property" >&2
+        echo "${0##*/}: line $LINENUMBER: key without a value - skipping property" >&2
         continue
       fi
     elif ((IGNORE_SECTION == 0)); then		# Process the property definition as a key/value pair.
@@ -463,7 +463,7 @@ parse_ini() {
           # Strip the quotes as they're not needed.
           VALUE="${VALUE:1:-1}"
         else
-          echo "${0##*/}: line $LINENUMBER: unmatched quotes - ignoring property" >&2
+          echo "${0##*/}: line $LINENUMBER: unmatched quotes - skipping property" >&2
           continue
         fi
       fi
